In [80]:
!pip install -Uqq ucimlrepo
!pip install -Uqq fastbook

In [81]:
from fastbook import *
import fastbook
fastbook.setup_book

In [82]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
real_estate_valuation = fetch_ucirepo(id=477) 
  
# data (as pandas dataframes) 
X = real_estate_valuation.data.features 
y = real_estate_valuation.data.targets 
  
# metadata 
#print(f"Metadata: ({real_estate_valuation.metadata})\n\n") 
  
# variable information 
#print(f"Variables: ({real_estate_valuation.variables})\n\n") 
print(f"Columns: {X.info()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 6 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   X1 transaction date                     414 non-null    float64
 1   X2 house age                            414 non-null    float64
 2   X3 distance to the nearest MRT station  414 non-null    float64
 3   X4 number of convenience stores         414 non-null    int64
 4   X5 latitude                             414 non-null    float64
 5   X6 longitude                            414 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 19.5 KB
Columns: None

In [83]:
from fastai.data.transforms import RandomSplitter
trn_split,val_split=RandomSplitter(seed=42)(X)

In [84]:
trn_indep, val_indep = X.iloc[trn_split], X.iloc[val_split]
trn_dep, val_dep = y.iloc[trn_split], y.iloc[val_split]
trn_indep.shape, trn_dep.shape, val_indep.shape, val_dep.shape

((332, 6), (332, 1), (82, 6), (82, 1))

In [85]:
trn_indep.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
290,2013.083,37.7,490.3446,0,24.97217,121.53471
383,2012.667,29.1,506.1144,4,24.97845,121.53889
226,2013.000,16.5,4082.0150,0,24.94155,121.50381
29,2013.083,7.1,451.2438,5,24.97563,121.54694
59,2013.083,13.3,336.0532,5,24.95776,121.53438

In [86]:
from fastai.imports import *

# Step 1: Create time features and normalize all independent variables

In [87]:
from sklearn import preprocessing
import numpy as np

def preprocess_independent_variables(indpt_vs, scaler = None):
    time_df = pd.DataFrame(index=indpt_vs.index)
    
    fractional, integral = np.modf(indpt_vs["X1 transaction date"])
    time_df["year"] = pd.Series(integral.astype(int))
    time_df["month"] = pd.Series(np.round(fractional*12))

    columns = ['X2 house age', 'X3 distance to the nearest MRT station', 'X4 number of convenience stores', 'X5 latitude', 'X6 longitude']
    indpt_vs_columns_df = pd.concat([time_df, indpt_vs[columns]], axis=1)
    
    min_max_scaler = scaler
    if min_max_scaler is None:
        s = preprocessing.MinMaxScaler()
        min_max_scaler = s.fit(indpt_vs_columns_df)
    indpt_vs_columns_minmax = min_max_scaler.transform(indpt_vs_columns_df)

    columns = ['year_norm', 'month_norm', "house_age",'distance_to_nearest_MRT_station', 'number_of_convenience_stores', 'latitude', 'longitude']
    df = pd.DataFrame(
        indpt_vs_columns_minmax,
        columns=columns,
        index=indpt_vs.index
    )
    return df, min_max_scaler

In [88]:
trn_indep, scaler = preprocess_independent_variables(trn_indep)
trn_indep.head()

,year_norm,month_norm,house_age,distance_to_nearest_MRT_station,number_of_convenience_stores,latitude,longitude
290,1.0,0.090909,0.860731,0.072233,0.0,0.485943,0.659694
383,0.0,0.727273,0.664384,0.074673,0.4,0.562046,0.704766
226,1.0,0.000000,0.376712,0.627820,0.0,0.114881,0.326504
29,1.0,0.090909,0.162100,0.066185,0.5,0.527872,0.791568
59,1.0,0.090909,0.303653,0.048366,0.5,0.311318,0.656135

# Step 2: Turn X and Y into tensors

In [89]:
idpnt_column_names = ['year_norm', 'month_norm', 'house_age', 'distance_to_nearest_MRT_station',
       'number_of_convenience_stores', 'latitude', 'longitude']
n_columns = len(idpnt_column_names)
train_indpt = tensor(trn_indep[idpnt_column_names])
n_columns, train_indpt[:5]

(7,
 tensor([[1.0000, 0.0909, 0.8607, 0.0722, 0.0000, 0.4859, 0.6597],
         [0.0000, 0.7273, 0.6644, 0.0747, 0.4000, 0.5620, 0.7048],
         [1.0000, 0.0000, 0.3767, 0.6278, 0.0000, 0.1149, 0.3265],
         [1.0000, 0.0909, 0.1621, 0.0662, 0.5000, 0.5279, 0.7916],
         [1.0000, 0.0909, 0.3037, 0.0484, 0.5000, 0.3113, 0.6561]]))

In [90]:
train_dpt = tensor(trn_dep)
train_dpt[:5]

tensor([[37.0000],
        [40.3000],
        [12.8000],
        [57.1000],
        [42.4000]])

# Step 3: Train linear model

In [91]:
def init_coeffs():
    coeffs = torch.rand(n_columns+1,1) - 0.5
    coeffs[-1] = 0.0
    return coeffs.requires_grad_()

In [92]:
def calc_preds(coeffs, train_indpt):
    weights = coeffs[:-1]
    intercept = coeffs[-1]
    return train_indpt @ weights + intercept

In [93]:
def calc_loss(coeffs, train_indpt, train_dep):
    preds = calc_preds(coeffs, train_indpt)
    return torch.abs(preds-train_dep).mean()

In [94]:
def update_coeffs(coeffs, lr=0.01):
    coeffs.sub_(coeffs.grad * lr)
    coeffs.grad.zero_()

In [95]:
def train_epoch(coeffs, lr=0.01):
    loss = calc_loss(coeffs, train_indpt, train_dpt)
    loss.backward()
    with torch.no_grad(): update_coeffs(coeffs, lr)
    print(f"{loss:.3}")

In [96]:
def train_model(epochs=30, lr=0.01):
    #torch.manual_seed(442)
    coeffs = init_coeffs()
    for i in range(epochs): train_epoch(coeffs, lr)
    return coeffs

In [97]:
coeffs = train_model(epochs=100,lr=6)

38.3
22.1
10.6
9.4
9.14
8.91
8.69
8.49
8.3
8.14
7.97
7.81
7.65
7.5
7.35
7.2
7.07
6.97
6.89
6.82
6.77
6.72
6.7
6.65
6.62
6.58
6.55
6.52
6.5
6.47
6.46
6.43
6.41
6.41
6.38
6.42
6.42
6.42
6.42
6.41
6.39
6.38
6.38
6.38
6.43
6.34
6.34
6.34
6.39
6.32
6.36
6.32
6.43
6.36
6.49
6.33
6.42
6.34
6.47
6.34
6.47
6.33
6.46
6.33
6.48
6.37
6.5
6.34
6.52
6.34
6.51
6.34
6.5
6.31
6.43
6.36
6.47
6.32
6.47
6.34
6.45
6.35
6.43
6.32
6.41
6.34
6.41
6.33
6.41
6.33
6.39
6.35
6.41
6.33
6.42
6.32
6.41
6.33
6.41
6.32

In [98]:
def measure_loss(coeffs): 
    ivs, _ = preprocess_independent_variables(val_indep, scaler=scaler)
    return calc_loss(coeffs, tensor(ivs), tensor(val_dep))

lin_loss = measure_loss(coeffs)
lin_loss

tensor(7.2097, grad_fn=<MeanBackward0>)

In [99]:
def show_coeffs(): return dict(zip(idpnt_column_names, coeffs))
show_coeffs()

{'year_norm': tensor([4.1862], grad_fn=<UnbindBackward0>),
 'month_norm': tensor([4.7464], grad_fn=<UnbindBackward0>),
 'house_age': tensor([-12.1699], grad_fn=<UnbindBackward0>),
 'distance_to_nearest_MRT_station': tensor([-11.5518], grad_fn=<UnbindBackward0>),
 'number_of_convenience_stores': tensor([14.1175], grad_fn=<UnbindBackward0>),
 'latitude': tensor([19.7563], grad_fn=<UnbindBackward0>),
 'longitude': tensor([14.4777], grad_fn=<UnbindBackward0>)}

In [100]:
val_ivs, _ = preprocess_independent_variables(val_indep, scaler=scaler)

test_item = 0
pred = calc_preds(coeffs, tensor(val_ivs)[test_item])
val_indep.iloc[test_item], val_dep.iloc[test_item],pred

(X1 transaction date                       2012.75000
 X2 house age                                16.10000
 X3 distance to the nearest MRT station    4066.58700
 X4 number of convenience stores              0.00000
 X5 latitude                                 24.94297
 X6 longitude                               121.50342
 Name: 384, dtype: float64,
 Y house price of unit area    12.9
 Name: 384, dtype: float64,
 tensor([16.2680], grad_fn=<AddBackward0>))

# Step 4: Train an ensemble of linear models

In [101]:
def ensemble():
    coeffs = train_model(epochs=30,lr=7)
    ivs, _ = preprocess_independent_variables(val_indep, scaler=scaler)
    return calc_preds(coeffs, tensor(ivs))

In [102]:
learns = [ensemble() for _ in range(100)]

38.6
19.9
9.75
9.38
9.07
8.81
8.56
8.35
8.15
7.96
7.77
7.59
7.41
7.24
7.09
7.02
6.9
6.88
6.78
6.8
6.71
6.69
6.6
6.61
6.55
6.59
6.58
6.71
6.51
6.56
37.9
19.2
9.57
9.25
8.97
8.71
8.47
8.26
8.06
7.87
7.68
7.5
7.33
7.17
7.03
6.92
6.83
6.77
6.72
6.68
6.66
6.62
6.57
6.54
6.52
6.48
6.48
6.56
6.64
6.5
37.8
19.1
9.54
9.23
8.94
8.68
8.44
8.23
8.03
7.84
7.66
7.48
7.3
7.14
7.01
6.9
6.82
6.78
6.74
6.68
6.64
6.62
6.56
6.53
6.53
6.52
6.53
6.59
6.72
6.51
38.8
20.1
9.81
9.44
9.12
8.85
8.6
8.38
8.19
7.99
7.8
7.62
7.44
7.27
7.11
6.98
6.88
6.82
6.77
6.75
6.68
6.65
6.59
6.54
6.51
6.52
6.5
6.53
6.55
6.64
38.0
19.3
9.58
9.27
8.98
8.71
8.48
8.26
8.07
7.88
7.69
7.51
7.34
7.17
7.02
6.92
6.84
6.8
6.73
6.7
6.65
6.61
6.57
6.54
6.5
6.49
6.46
6.44
6.52
6.62
38.6
19.9
9.73
9.36
9.06
8.79
8.55
8.33
8.13
7.93
7.75
7.56
7.39
7.22
7.06
6.96
6.87
6.82
6.76
6.73
6.66
6.62
6.57
6.54
6.5
6.49
6.47
6.46
6.52
6.62
37.5
18.9
9.68
9.37
9.08
8.81
8.56
8.35
8.15
7.95
7.77
7.58
7.41
7.24
7.09
6.96
6.87
6.8
6.74
6.71
6.66
6.63
6.59
6.56
6.51
6.52
6.49
6.46
6.51
6.62
38.6
19.8
9.71
9.36
9.05
8.79
8.54
8.33
8.12
7.93
7.74
7.56
7.39
7.22
7.06
6.95
6.86
6.8
6.74
6.7
6.64
6.61
6.58
6.54
6.51
6.51
6.49
6.52
6.55
6.68
37.9
19.2
9.55
9.23
8.95
8.7
8.47
8.27
8.08
7.89
7.7
7.52
7.35
7.18
7.04
6.92
6.86
6.81
6.8
6.73
6.71
6.65
6.65
6.65
6.69
6.53
6.55
6.56
6.67
6.5
38.2
19.4
9.62
9.29
9.0
8.73
8.49
8.28
8.09
7.9
7.71
7.53
7.36
7.19
7.04
6.93
6.85
6.79
6.75
6.69
6.68
6.61
6.58
6.54
6.52
6.48
6.47
6.46
6.47
6.54
38.3
19.6
9.71
9.36
9.06
8.8
8.57
8.36
8.16
7.97
7.78
7.6
7.43
7.25
7.1
6.97
6.89
6.84
6.76
6.73
6.67
6.64
6.59
6.55
6.51
6.51
6.46
6.46
6.52
6.62
38.9
20.2
9.76
9.37
9.05
8.79
8.54
8.33
8.12
7.93
7.74
7.56
7.39
7.22
7.06
6.95
6.87
6.83
6.76
6.75
6.66
6.63
6.57
6.53
6.5
6.49
6.47
6.48
6.57
6.74
38.0
19.3
9.52
9.2
8.93
8.68
8.45
8.25
8.05
7.86
7.68
7.5
7.33
7.16
7.02
6.91
6.83
6.76
6.72
6.68
6.65
6.61
6.56
6.52
6.51
6.47
6.47
6.51
6.6
6.53
38.4
19.7
9.62
9.29
8.99
8.74
8.51
8.3
8.11
7.91
7.73
7.55
7.37
7.2
7.06
6.98
6.88
6.88
6.8
6.79
6.68
6.67
6.6
6.63
6.61
6.66
6.5
6.52
6.56
6.7
37.6
19.0
9.58
9.27
8.99
8.72
8.47
8.26
8.06
7.87
7.68
7.5
7.33
7.16
7.03
6.92
6.84
6.79
6.74
6.69
6.65
6.6
6.57
6.53
6.53
6.49
6.46
6.48
6.5
6.52
37.7
19.1
9.61
9.3
9.0
8.74
8.49
8.28
8.09
7.89
7.71
7.53
7.36
7.18
7.03
6.94
6.86
6.82
6.72
6.69
6.63
6.61
6.57
6.54
6.5
6.48
6.48
6.49
6.55
6.67
38.4
19.7
9.64
9.31
9.01
8.75
8.5
8.29
8.1
7.91
7.72
7.54
7.36
7.19
7.05
6.95
6.9
6.8
6.77
6.67
6.64
6.59
6.57
6.52
6.51
6.48
6.47
6.45
6.47
6.55
37.8
19.2
9.65
9.34
9.05
8.79
8.55
8.34
8.14
7.95
7.76
7.58
7.41
7.24
7.09
6.96
6.89
6.83
6.76
6.73
6.67
6.64
6.58
6.54
6.51
6.49
6.46
6.45
6.49
6.53
39.4
20.6
9.74
9.35
9.04
8.77
8.52
8.29
8.1
7.9
7.71
7.53
7.36
7.19
7.04
6.94
6.85
6.81
6.73
6.69
6.63
6.6
6.56
6.52
6.48
6.5
6.48
6.52
6.54
6.65
38.1
19.4
9.6
9.28
8.99
8.73
8.49
8.28
8.08
7.89
7.71
7.53
7.35
7.19
7.04
6.94
6.86
6.81
6.77
6.69
6.65
6.61
6.57
6.52
6.5
6.46
6.48
6.55
6.64
6.49
38.3
19.6
9.66
9.33
9.04
8.78
8.54
8.32
8.12
7.93
7.74
7.56
7.39
7.22
7.08
6.95
6.88
6.82
6.78
6.69
6.67
6.62
6.59
6.55
6.53
6.49
6.47
6.44
6.44
6.52
38.2
19.5
9.67
9.35
9.05
8.78
8.53
8.32
8.13
7.93
7.75
7.56
7.39
7.22
7.06
6.95
6.88
6.84
6.76
6.71
6.64
6.63
6.58
6.55
6.51
6.51
6.49
6.45
6.51
6.58
38.6
19.8
9.61
9.27
8.98
8.72
8.5
8.28
8.09
7.9
7.71
7.53
7.36
7.19
7.05
6.93
6.84
6.77
6.72
6.68
6.66
6.63
6.59
6.53
6.53
6.48
6.47
6.48
6.49
6.53
38.4
19.7
9.6
9.26
8.97
8.71
8.48
8.27
8.07
7.89
7.7
7.51
7.34
7.17
7.03
6.91
6.83
6.77
6.75
6.68
6.67
6.6
6.56
6.53
6.51
6.47
6.45
6.43
6.42
6.51
37.7
19.0
9.66
9.34
9.04
8.77
8.52
8.3
8.1
7.91
7.72
7.54
7.36
7.19
7.05
6.93
6.84
6.79
6.74
6.68
6.64
6.61
6.57
6.53
6.52
6.47
6.46
6.53
6.64
6.49
38.5
19.8
9.66
9.32
9.02
8.75
8.5
8.27
8.07
7.88
7.69
7.51
7.34
7.17
7.02
6.91
6.84
6.78
6.72
6.69
6.63
6.61
6.56
6.53
6.5
6.5
6.49
6.51
6.55
6.7
38.3
19.6
9.63
9.29
9.0
8.73
8.49
8.27
8.07
7.88
7.7
7.52
7.34
7.17
7.03
6.91
6.83
6.76
6.71
6.66
6.64
6.6
6.57
6.52
6.51
6.46
6.46
6.44
6.46
6.54
38.4
19.7
9.64
9.31
9.0
8.73
8.48
8.27
8.07
7.88
7.69
7.51
7.33
7.16
7.02
6.91
6.83
6.77
6.73
6.67
6.63
6.6
6.57
6.53
6.53
6.51
6.52
6.58
6.74
6.48
38.4
19.7
9.63
9.29
8.99
8.73
8.48
8.27
8.08
7.89
7.7
7.52
7.35
7.17
7.03
6.93
6.85
6.8
6.73
6.69
6.63
6.6
6.55
6.52
6.47
6.49
6.49
6.5
6.55
6.66
37.8
19.2
9.65
9.33
9.03
8.76
8.52
8.3
8.11
7.92
7.73
7.54
7.37
7.2
7.06
6.94
6.85
6.79
6.73
6.7
6.66
6.61
6.58
6.55
6.5
6.52
6.53
6.56
6.52
6.65
38.1
19.4
9.67
9.34
9.04
8.77
8.52
8.31
8.1
7.91
7.72
7.53
7.36
7.19
7.04
6.93
6.84
6.78
6.74
6.69
6.64
6.61
6.57
6.55
6.5
6.5
6.48
6.51
6.56
6.67
38.1
19.4
9.64
9.31
9.01
8.76
8.53
8.31
8.11
7.92
7.73
7.55
7.38
7.21
7.06
6.94
6.85
6.78
6.75
6.73
6.66
6.63
6.59
6.55
6.52
6.51
6.48
6.49
6.58
6.74
38.4
19.7
9.68
9.33
9.03
8.76
8.51
8.3
8.1
7.91
7.72
7.54
7.36
7.19
7.04
6.93
6.84
6.78
6.73
6.7
6.65
6.6
6.56
6.54
6.51
6.49
6.45
6.44
6.49
6.51
37.9
19.2
9.58
9.26
8.96
8.69
8.44
8.22
8.02
7.82
7.64
7.45
7.28
7.11
6.98
6.88
6.81
6.74
6.7
6.67
6.62
6.59
6.55
6.54
6.5
6.5
6.51
6.55
6.49
6.6
37.2
18.6
9.63
9.32
9.03
8.76
8.52
8.31
8.11
7.92
7.73
7.55
7.38
7.21
7.06
6.94
6.86
6.82
6.79
6.74
6.71
6.62
6.58
6.54
6.53
6.49
6.48
6.49
6.5
6.53
38.6
19.8
9.65
9.3
8.99
8.73
8.48
8.26
8.07
7.87
7.69
7.51
7.33
7.16
7.01
6.91
6.84
6.79
6.76
6.67
6.65
6.59
6.55
6.52
6.5
6.48
6.45
6.51
6.63
6.47
37.7
19.0
9.66
9.34
9.04
8.77
8.52
8.3
8.1
7.91
7.72
7.54
7.37
7.2
7.04
6.94
6.87
6.83
6.74
6.69
6.63
6.59
6.57
6.54
6.51
6.49
6.47
6.49
6.58
6.71
38.2
19.5
9.51
9.2
8.9
8.65
8.43
8.21
8.02
7.83
7.64
7.46
7.29
7.13
6.99
6.89
6.85
6.77
6.72
6.66
6.62
6.59
6.55
6.51
6.52
6.49
6.51
6.58
6.74
6.48
38.5
19.7
9.61
9.27
8.97
8.71
8.46
8.24
8.04
7.85
7.66
7.48
7.31
7.14
7.0
6.9
6.83
6.76
6.7
6.67
6.62
6.59
6.53
6.52
6.46
6.48
6.48
6.52
6.51
6.63
37.5
18.8
9.6
9.28
9.0
8.73
8.49
8.27
8.07
7.88
7.69
7.51
7.34
7.17
7.03
6.92
6.85
6.79
6.74
6.69
6.65
6.61
6.57
6.54
6.54
6.51
6.53
6.57
6.65
6.48
38.1
19.4
9.65
9.33
9.03
8.77
8.52
8.31
8.11
7.92
7.73
7.54
7.37
7.2
7.05
6.96
6.89
6.87
6.78
6.78
6.68
6.63
6.56
6.53
6.49
6.49
6.47
6.44
6.49
6.53
37.8
19.1
9.61
9.29
9.0
8.74
8.49
8.28
8.08
7.89
7.7
7.52
7.34
7.18
7.03
6.92
6.85
6.8
6.73
6.69
6.63
6.6
6.56
6.53
6.48
6.48
6.47
6.47
6.55
6.64
38.3
19.6
9.72
9.38
9.07
8.8
8.55
8.34
8.13
7.94
7.74
7.56
7.38
7.21
7.06
6.95
6.88
6.83
6.74
6.72
6.64
6.62
6.57
6.54
6.51
6.51
6.47
6.45
6.49
6.52
37.7
19.0
9.47
9.17
8.89
8.64
8.4
8.19
7.99
7.8
7.62
7.44
7.27
7.1
6.97
6.87
6.79
6.73
6.68
6.63
6.59
6.56
6.55
6.5
6.49
6.46
6.45
6.46
6.48
6.5
38.5
19.7
9.58
9.26
8.96
8.69
8.45
8.24
8.05
7.85
7.67
7.49
7.32
7.15
7.01
6.91
6.85
6.8
6.79
6.73
6.7
6.64
6.62
6.58
6.62
6.56
6.63
6.48
6.5
6.52
38.2
19.5
9.63
9.3
9.01
8.74
8.5
8.28
8.09
7.89
7.7
7.52
7.35
7.18
7.03
6.92
6.83
6.78
6.74
6.68
6.65
6.61
6.57
6.53
6.54
6.51
6.55
6.55
6.64
6.49
38.1
19.4
9.77
9.43
9.12
8.84
8.59
8.36
8.16
7.97
7.78
7.59
7.42
7.24
7.08
6.95
6.86
6.78
6.73
6.71
6.65
6.63
6.58
6.54
6.49
6.49
6.46
6.45
6.49
6.55
38.1
19.4
9.65
9.32
9.03
8.76
8.51
8.3
8.1
7.91
7.72
7.54
7.36
7.2
7.07
6.98
6.96
6.85
6.92
6.84
6.84
6.68
6.68
6.62
6.66
6.58
6.61
6.53
6.58
6.49
38.4
19.7
9.73
9.38
9.07
8.81
8.57
8.35
8.16
7.97
7.78
7.59
7.42
7.25
7.09
6.98
6.9
6.9
6.81
6.8
6.73
6.71
6.63
6.65
6.62
6.67
6.52
6.56
6.53
6.63
37.6
18.9
9.57
9.26
8.98
8.72
8.48
8.27
8.08
7.88
7.7
7.52
7.35
7.18
7.05
6.96
6.93
6.81
6.79
6.72
6.68
6.61
6.57
6.53
6.53
6.48
6.47
6.54
6.63
6.5
38.2
19.4
9.62
9.3
9.0
8.73
8.49
8.26
8.07
7.87
7.69
7.5
7.33
7.15
7.01
6.9
6.82
6.76
6.73
6.66
6.63
6.6
6.56
6.51
6.5
6.46
6.46
6.5
6.54
6.46
38.3
19.6
9.61
9.28
8.98
8.72
8.48
8.26
8.07
7.88
7.69
7.51
7.34
7.17
7.03
6.92
6.85
6.79
6.72
6.7
6.63
6.61
6.58
6.53
6.5
6.5
6.5
6.54
6.52
6.6
38.9
20.1
9.78
9.4
9.08
8.81
8.57
8.35
8.15
7.95
7.77
7.58
7.41
7.24
7.08
6.98
6.89
6.92
6.84
6.83
6.75
6.7
6.65
6.68
6.58
6.65
6.52
6.52
6.56
6.7
38.1
19.4
9.58
9.25
8.96
8.71
8.49
8.27
8.07
7.88
7.69
7.51
7.34
7.17
7.03
6.94
6.89
6.79
6.77
6.71
6.68
6.59
6.56
6.53
6.5
6.48
6.45
6.5
6.55
6.47
37.4
18.8
9.59
9.27
8.99
8.73
8.48
8.27
8.07
7.88
7.69
7.51
7.34
7.17
7.03
6.92
6.85
6.82
6.73
6.69
6.63
6.61
6.57
6.54
6.5
6.49
6.48
6.53
6.53
6.66
37.9
19.2
9.45
9.15
8.88
8.63
8.41
8.2
8.01
7.82
7.64
7.46
7.28
7.12
7.0
6.93
6.95
6.82
6.83
6.73
6.7
6.63
6.62
6.58
6.66
6.53
6.55
6.54
6.64
6.48
38.4
19.7
9.68
9.35
9.05
8.79
8.55
8.34
8.14
7.95
7.76
7.58
7.4
7.23
7.08
6.95
6.88
6.83
6.75
6.71
6.64
6.62
6.58
6.55
6.51
6.51
6.49
6.5
6.59
6.75
37.7
19.0
9.57
9.26
8.97
8.72
8.48
8.27
8.08
7.89
7.7
7.52
7.35
7.18
7.03
6.92
6.86
6.8
6.76
6.7
6.66
6.61
6.57
6.52
6.51
6.48
6.47
6.51
6.59
6.53
37.8
19.1
9.58
9.27
8.98
8.72
8.47
8.26
8.06
7.87
7.68
7.5
7.33
7.16
7.02
6.91
6.83
6.79
6.73
6.68
6.65
6.6
6.56
6.51
6.5
6.45
6.48
6.59
6.7
6.52
38.2
19.5
9.66
9.33
9.04
8.77
8.52
8.31
8.12
7.92
7.74
7.56
7.38
7.21
7.06
6.99
6.89
6.86
6.77
6.74
6.68
6.63
6.58
6.55
6.5
6.5
6.49
6.49
6.54
6.65
37.9
19.2
9.64
9.32
9.02
8.76
8.52
8.3
8.1
7.91
7.72
7.54
7.37
7.21
7.06
6.96
6.87
6.8
6.76
6.7
6.67
6.62
6.58
6.54
6.52
6.49
6.48
6.5
6.57
6.47
38.1
19.4
9.65
9.32
9.02
8.76
8.52
8.31
8.11
7.92
7.73
7.55
7.38
7.2
7.06
6.95
6.91
6.8
6.79
6.71
6.68
6.6
6.56
6.55
6.51
6.48
6.46
6.46
6.46
6.55
38.2
19.5
9.6
9.28
8.98
8.72
8.47
8.25
8.06
7.86
7.68
7.5
7.32
7.16
7.02
6.91
6.83
6.79
6.74
6.67
6.65
6.6
6.56
6.52
6.52
6.46
6.49
6.53
6.63
6.49
38.2
19.5
9.61
9.29
8.99
8.73
8.49
8.28
8.08
7.89
7.7
7.52
7.34
7.18
7.03
6.92
6.85
6.81
6.73
6.69
6.63
6.6
6.56
6.54
6.5
6.5
6.46
6.45
6.48
6.56
38.6
19.8
9.57
9.24
8.95
8.69
8.45
8.24
8.04
7.85
7.66
7.48
7.31
7.15
7.01
6.92
6.88
6.79
6.78
6.71
6.69
6.63
6.63
6.6
6.66
6.52
6.56
6.54
6.64
6.48
38.9
20.1
9.64
9.29
9.0
8.73
8.49
8.27
8.07
7.88
7.69
7.51
7.34
7.17
7.03
6.92
6.84
6.79
6.73
6.7
6.64
6.61
6.58
6.54
6.5
6.49
6.46
6.44
6.55
6.65
38.3
19.6
9.66
9.32
9.03
8.76
8.52
8.3
8.1
7.91
7.72
7.54
7.36
7.19
7.04
6.93
6.86
6.82
6.73
6.7
6.64
6.6
6.56
6.53
6.49
6.48
6.47
6.45
6.54
6.66
38.4
19.7
9.62
9.28
8.99
8.73
8.49
8.28
8.08
7.89
7.7
7.52
7.35
7.18
7.04
6.93
6.84
6.78
6.73
6.7
6.64
6.62
6.58
6.54
6.5
6.51
6.47
6.46
6.54
6.62
37.7
19.0
9.62
9.31
9.02
8.75
8.51
8.29
8.09
7.89
7.71
7.52
7.35
7.18
7.03
6.92
6.83
6.77
6.74
6.68
6.65
6.61
6.56
6.52
6.52
6.49
6.47
6.52
6.65
6.48
37.5
18.8
9.46
9.16
8.89
8.64
8.41
8.21
8.01
7.82
7.64
7.46
7.29
7.13
7.01
6.93
6.9
6.79
6.78
6.7
6.66
6.59
6.56
6.53
6.51
6.49
6.48
6.56
6.64
6.48
38.2
19.5
9.62
9.3
9.0
8.74
8.5
8.29
8.09
7.9
7.71
7.53
7.36
7.19
7.05
6.93
6.84
6.78
6.73
6.69
6.66
6.62
6.58
6.53
6.52
6.49
6.48
6.47
6.49
6.53
38.3
19.6
9.68
9.34
9.04
8.77
8.52
8.31
8.11
7.91
7.73
7.54
7.37
7.2
7.05
6.93
6.85
6.79
6.74
6.69
6.65
6.6
6.57
6.53
6.51
6.47
6.46
6.48
6.5
6.52
38.4
19.7
9.68
9.33
9.02
8.75
8.51
8.29
8.09
7.89
7.71
7.53
7.35
7.18
7.04
6.93
6.86
6.8
6.75
6.72
6.65
6.61
6.57
6.53
6.49
6.49
6.5
6.5
6.53
6.66
38.8
20.0
9.65
9.3
9.0
8.73
8.49
8.27
8.08
7.88
7.7
7.52
7.34
7.17
7.03
6.92
6.86
6.8
6.81
6.74
6.73
6.63
6.62
6.56
6.56
6.55
6.62
6.47
6.49
6.51
37.7
19.0
9.54
9.23
8.95
8.69
8.44
8.24
8.04
7.85
7.66
7.48
7.31
7.15
7.01
6.9
6.82
6.78
6.74
6.68
6.65
6.62
6.57
6.54
6.52
6.48
6.47
6.48
6.5
6.53
38.7
20.0
9.67
9.32
9.02
8.75
8.51
8.29
8.09
7.9
7.71
7.53
7.36
7.19
7.03
6.95
6.89
6.95
6.82
6.8
6.7
6.67
6.6
6.61
6.59
6.65
6.49
6.5
6.54
6.68
38.2
19.5
9.6
9.27
8.97
8.7
8.47
8.25
8.06
7.87
7.68
7.5
7.33
7.16
7.01
6.9
6.81
6.76
6.71
6.69
6.64
6.62
6.56
6.53
6.49
6.49
6.47
6.48
6.54
6.68
38.2
19.5
9.51
9.2
8.91
8.66
8.43
8.22
8.03
7.83
7.65
7.47
7.3
7.14
7.01
6.91
6.88
6.78
6.73
6.66
6.64
6.6
6.56
6.52
6.53
6.52
6.55
6.55
6.63
6.49
38.1
19.4
9.63
9.31
9.01
8.74
8.5
8.29
8.1
7.9
7.71
7.53
7.36
7.19
7.04
6.92
6.83
6.76
6.7
6.65
6.61
6.58
6.57
6.53
6.48
6.48
6.44
6.43
6.45
6.47
38.5
19.8
9.68
9.33
9.03
8.77
8.53
8.32
8.13
7.94
7.75
7.56
7.39
7.22
7.07
6.95
6.87
6.8
6.75
6.7
6.67
6.62
6.58
6.53
6.52
6.48
6.46
6.46
6.47
6.54
37.5
18.8
9.58
9.27
8.99
8.73
8.49
8.28
8.08
7.89
7.7
7.52
7.35
7.18
7.05
6.94
6.89
6.8
6.76
6.7
6.67
6.61
6.58
6.54
6.54
6.48
6.49
6.55
6.66
6.51
37.4
18.8
9.61
9.29
9.02
8.75
8.52
8.3
8.1
7.91
7.72
7.54
7.37
7.2
7.06
6.95
6.9
6.81
6.77
6.68
6.66
6.62
6.58
6.53
6.52
6.48
6.48
6.5
6.53
6.5
39.0
20.2
9.72
9.36
9.06
8.78
8.54
8.31
8.11
7.92
7.73
7.55
7.37
7.2
7.05
6.93
6.86
6.83
6.74
6.71
6.64
6.61
6.56
6.53
6.49
6.5
6.49
6.51
6.55
6.65
37.6
18.9
9.63
9.32
9.02
8.75
8.51
8.29
8.09
7.9
7.71
7.53
7.36
7.19
7.05
6.93
6.86
6.79
6.75
6.68
6.66
6.62
6.57
6.54
6.54
6.52
6.53
6.56
6.63
6.5
37.4
18.7
9.5
9.19
8.92
8.66
8.43
8.22
8.03
7.84
7.65
7.47
7.3
7.14
7.01
6.92
6.86
6.77
6.73
6.68
6.65
6.6
6.56
6.51
6.51
6.47
6.47
6.52
6.63
6.49
37.7
19.0
9.61
9.3
9.01
8.75
8.5
8.28
8.09
7.89
7.7
7.52
7.35
7.18
7.04
6.93
6.86
6.83
6.75
6.71
6.64
6.62
6.58
6.55
6.52
6.5
6.48
6.47
6.52
6.64
38.1
19.4
9.54
9.22
8.93
8.67
8.43
8.21
8.01
7.82
7.64
7.46
7.28
7.12
6.98
6.88
6.8
6.73
6.68
6.65
6.63
6.6
6.56
6.51
6.51
6.46
6.46
6.55
6.65
6.5
38.1
19.4
9.69
9.36
9.06
8.79
8.55
8.32
8.12
7.93
7.74
7.56
7.38
7.21
7.06
6.95
6.87
6.82
6.74
6.7
6.63
6.61
6.57
6.54
6.5
6.5
6.5
6.54
6.53
6.62
38.0
19.3
9.63
9.32
9.02
8.77
8.54
8.32
8.12
7.93
7.74
7.56
7.39
7.22
7.07
6.95
6.86
6.79
6.73
6.69
6.65
6.63
6.6
6.55
6.52
6.53
6.48
6.48
6.54
6.64
38.5
19.8
9.59
9.26
8.97
8.73
8.49
8.28
8.08
7.89
7.71
7.53
7.36
7.19
7.05
6.95
6.9
6.79
6.75
6.68
6.66
6.62
6.58
6.52
6.51
6.46
6.46
6.46
6.47
6.53
38.8
20.1
9.71
9.34
9.04
8.77
8.53
8.31
8.1
7.91
7.72
7.54
7.37
7.2
7.05
6.93
6.85
6.79
6.73
6.69
6.66
6.62
6.57
6.52
6.49
6.47
6.46
6.51
6.58
6.48
38.2
19.5
9.7
9.37
9.07
8.8
8.55
8.33
8.13
7.94
7.75
7.57
7.39
7.22
7.06
6.96
6.88
6.83
6.74
6.71
6.66
6.62
6.58
6.54
6.51
6.51
6.49
6.51
6.59
6.75
37.4
18.7
9.6
9.28
9.0
8.73
8.48
8.27
8.07
7.88
7.69
7.5
7.33
7.16
7.02
6.92
6.84
6.8
6.73
6.69
6.63
6.59
6.57
6.54
6.51
6.5
6.48
6.5
6.58
6.72
38.2
19.5
9.65
9.32
9.02
8.75
8.5
8.27
8.08
7.88
7.69
7.51
7.34
7.17
7.02
6.92
6.82
6.76
6.71
6.66
6.61
6.57
6.57
6.52
6.51
6.47
6.47
6.51
6.64
6.49
37.5
18.9
9.59
9.28
8.99
8.74
8.51
8.3
8.11
7.92
7.73
7.55
7.37
7.21
7.06
6.95
6.88
6.81
6.77
6.67
6.66
6.62
6.58
6.53
6.5
6.47
6.49
6.5
6.52
6.5
38.6
19.9
9.68
9.33
9.02
8.75
8.5
8.28
8.08
7.89
7.7
7.51
7.34
7.17
7.02
6.94
6.85
6.82
6.73
6.7
6.63
6.58
6.55
6.52
6.49
6.48
6.48
6.49
6.54
6.65
38.4
19.7
9.84
9.48
9.17
8.9
8.64
8.41
8.21
8.01
7.82
7.63
7.46
7.28
7.12
6.99
6.89
6.81
6.75
6.73
6.66
6.63
6.61
6.6
6.54
6.51
6.47
6.47
6.54
6.63
38.2
19.5
9.58
9.26
8.96
8.7
8.45
8.24
8.05
7.85
7.67
7.49
7.32
7.15
7.01
6.91
6.82
6.76
6.72
6.67
6.64
6.61
6.57
6.53
6.53
6.47
6.47
6.5
6.51
6.52
38.2
19.5
9.59
9.27
8.98
8.73
8.5
8.29
8.09
7.9
7.72
7.54
7.36
7.19
7.05
6.93
6.87
6.81
6.81
6.73
6.72
6.64
6.63
6.59
6.68
6.53
6.54
6.56
6.67
6.48
37.7
19.1
9.71
9.39
9.09
8.82
8.57
8.35
8.14
7.95
7.76
7.57
7.4
7.23
7.07
6.95
6.85
6.78
6.72
6.67
6.64
6.62
6.58
6.54
6.51
6.5
6.45
6.46
6.51
6.65

In [103]:
ens_preds = torch.stack(learns).mean(0)

In [104]:
lin_ens_loss = torch.abs(ens_preds-tensor(val_dep)).mean()
lin_ens_loss

tensor(6.8811, grad_fn=<MeanBackward0>)

In [105]:
# Calculate MAE separately for each existing linear-model prediction.
with torch.no_grad():
    val_targets = tensor(val_dep)
    lin_member_maes = torch.stack([
        torch.abs(preds - val_targets).mean()
        for preds in learns
    ])

# Save the summary before "learns" is reused for neural networks.
lin_ensemble_summary = {
    "Model family": "Linear",
    "Mean individual MAE": lin_member_maes.mean().item(),
    "Lowest individual MAE": lin_member_maes.min().item(),
    "Ensemble MAE": lin_ens_loss.item(),
}

pd.DataFrame([lin_ensemble_summary]).round(4)

  Model family  Mean individual MAE  Lowest individual MAE  Ensemble MAE
0       Linear               7.0455                 6.7146        6.8811

# Step 5: Train neural net

In [106]:
def init_coeffs(n_hidden = 10):
    layer1 = (torch.rand(n_columns, n_hidden)-0.5).requires_grad_()
    layer2 = (torch.rand(n_hidden, 1)-.3).requires_grad_()
    const = torch.rand(1)[0].requires_grad_()
    return layer1, layer2, const

In [107]:
import torch.nn.functional as F

def calc_preds(coeffs, indpts):
    l1, l2, c = coeffs
    r = F.relu(indpts@l1)
    return r@l2 + c

In [108]:
def update_coeffs(coeffs, lr):
    for c in coeffs:
        c.sub_(c.grad * lr)
        c.grad.zero_()

In [109]:
coeffs = train_model(epochs=70,lr=1e-1)

37.3
37.0
36.6
36.1
35.6
34.9
34.2
33.2
32.0
30.5
28.7
26.4
23.5
19.9
15.9
12.1
9.88
9.26
9.12
9.0
8.9
8.8
8.7
8.61
8.52
8.43
8.36
8.29
8.21
8.14
8.07
8.01
7.95
7.89
7.82
7.76
7.71
7.65
7.59
7.53
7.47
7.41
7.35
7.29
7.24
7.19
7.15
7.12
7.08
7.05
7.02
6.99
6.96
6.94
6.91
6.89
6.87
6.85
6.83
6.81
6.8
6.78
6.76
6.75
6.73
6.72
6.71
6.7
6.69
6.68

In [110]:
def measure_loss(coeffs): 
    ivs, _ = preprocess_independent_variables(val_indep, scaler=scaler)
    return calc_loss(coeffs, tensor(ivs), tensor(val_dep))

nn_loss = measure_loss(coeffs)
nn_loss

tensor(7.1803, grad_fn=<MeanBackward0>)

# Step 6: Train an ensemble of neural networks

In [111]:
def ensemble():
    coeffs = train_model(epochs=100,lr=1.5e-1)
    ivs, _ = preprocess_independent_variables(val_indep, scaler=scaler)
    return calc_preds(coeffs, tensor(ivs))

In [112]:
learns = [ensemble() for _ in range(100)]

37.3
36.9
36.5
36.0
35.4
34.7
33.7
32.4
30.6
28.0
24.5
19.7
14.0
10.2
9.4
9.21
9.03
8.86
8.7
8.54
8.39
8.25
8.12
7.99
7.87
7.77
7.66
7.57
7.47
7.38
7.29
7.21
7.14
7.07
7.01
6.95
6.9
6.86
6.83
6.8
6.77
6.74
6.71
6.69
6.67
6.65
6.63
6.62
6.61
6.6
6.59
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.48
6.47
6.46
6.45
6.44
6.43
6.42
6.42
6.41
6.4
6.39
6.38
6.38
6.37
6.36
6.36
6.34
6.33
6.33
6.32
6.31
6.3
6.29
6.28
6.27
6.26
6.26
6.25
6.25
6.25
6.23
6.22
6.22
6.22
6.21
6.2
6.19
6.2
6.19
6.2
37.6
37.3
37.0
36.7
36.2
35.7
34.9
33.9
32.5
30.6
28.0
24.2
19.2
13.4
9.93
9.41
9.22
9.04
8.87
8.7
8.55
8.41
8.28
8.15
8.03
7.92
7.82
7.72
7.63
7.53
7.44
7.35
7.27
7.18
7.11
7.05
6.99
6.94
6.89
6.85
6.82
6.79
6.76
6.74
6.71
6.69
6.67
6.65
6.63
6.62
6.6
6.59
6.58
6.57
6.56
6.54
6.54
6.53
6.52
6.51
6.5
6.49
6.48
6.47
6.47
6.46
6.45
6.44
6.44
6.43
6.42
6.42
6.41
6.4
6.4
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.32
6.32
6.31
6.31
6.3
6.3
6.3
6.29
6.29
6.29
6.29
6.28
36.8
36.2
35.5
34.5
33.2
31.4
29.0
25.6
20.8
14.7
10.2
9.14
8.95
8.78
8.62
8.46
8.31
8.18
8.06
7.95
7.84
7.74
7.64
7.55
7.46
7.37
7.28
7.19
7.12
7.06
7.01
6.96
6.92
6.88
6.84
6.81
6.79
6.76
6.73
6.71
6.69
6.67
6.66
6.65
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.51
6.5
6.49
6.49
6.48
6.47
6.47
6.46
6.45
6.44
6.44
6.43
6.43
6.42
6.41
6.41
6.4
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.35
6.35
6.34
6.34
6.34
6.33
6.33
6.33
6.33
6.32
6.32
6.32
6.31
6.31
6.31
6.31
37.3
36.9
36.4
35.8
35.0
33.8
32.3
30.2
27.2
23.1
17.6
11.8
9.43
9.19
9.02
8.85
8.69
8.55
8.41
8.28
8.16
8.05
7.95
7.86
7.76
7.67
7.58
7.49
7.41
7.32
7.25
7.18
7.12
7.07
7.02
6.97
6.93
6.9
6.87
6.84
6.81
6.78
6.76
6.74
6.72
6.7
6.68
6.67
6.65
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.48
6.47
6.47
6.46
6.45
6.44
6.43
6.42
6.41
6.41
6.39
6.39
6.38
6.37
6.36
6.35
6.34
6.33
6.33
6.32
6.32
6.31
6.3
6.3
6.29
6.29
6.28
6.27
6.27
6.26
6.26
6.25
6.25
6.24
6.24
6.23
6.23
37.1
36.8
36.4
36.0
35.4
34.7
33.8
32.6
30.8
28.5
25.2
20.6
15.1
10.7
9.45
9.27
9.09
8.93
8.77
8.62
8.49
8.35
8.22
8.1
7.99
7.88
7.77
7.67
7.57
7.48
7.39
7.3
7.21
7.12
7.05
6.98
6.92
6.87
6.82
6.78
6.75
6.72
6.69
6.66
6.64
6.62
6.59
6.57
6.56
6.54
6.53
6.51
6.5
6.49
6.48
6.47
6.46
6.45
6.44
6.43
6.42
6.42
6.41
6.4
6.39
6.39
6.38
6.37
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.32
6.31
6.31
6.3
6.3
6.3
6.29
6.28
6.28
6.27
6.27
6.27
6.26
6.26
6.25
6.25
6.25
6.24
6.24
6.24
6.24
6.24
6.24
6.25
6.24
36.9
36.4
35.7
34.9
33.8
32.4
30.4
27.7
23.8
18.7
13.0
9.85
9.47
9.3
9.14
8.97
8.82
8.67
8.54
8.41
8.3
8.19
8.08
7.98
7.88
7.79
7.7
7.61
7.53
7.45
7.37
7.29
7.22
7.16
7.11
7.06
7.02
6.98
6.94
6.91
6.88
6.85
6.83
6.8
6.77
6.75
6.73
6.71
6.7
6.68
6.67
6.66
6.64
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.57
6.55
6.55
6.54
6.53
6.52
6.51
6.5
6.5
6.49
6.48
6.47
6.46
6.46
6.45
6.44
6.43
6.42
6.41
6.41
6.4
6.39
6.39
6.38
6.37
6.38
6.36
6.37
6.36
6.38
6.37
6.37
6.36
6.37
6.35
6.35
6.33
6.35
6.31
6.33
36.8
36.4
35.8
35.2
34.3
33.1
31.5
29.2
26.1
21.7
16.2
11.3
9.73
9.53
9.34
9.17
9.01
8.85
8.7
8.57
8.44
8.31
8.19
8.08
7.97
7.87
7.77
7.67
7.58
7.49
7.4
7.32
7.25
7.18
7.12
7.06
7.01
6.97
6.93
6.9
6.86
6.83
6.81
6.79
6.76
6.77
6.71
6.7
6.67
6.65
6.63
6.62
6.61
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.51
6.5
6.49
6.48
6.47
6.46
6.45
6.43
6.42
6.41
6.4
6.39
6.38
6.37
6.36
6.34
6.33
6.32
6.31
6.3
6.29
6.28
6.26
6.25
6.24
6.23
6.22
6.21
6.2
6.2
6.2
6.2
6.18
6.18
6.18
6.17
6.16
6.16
6.15
6.14
37.2
36.7
36.1
35.2
34.0
32.4
30.2
27.1
22.7
16.9
11.0
9.11
8.93
8.77
8.63
8.5
8.36
8.25
8.13
8.03
7.93
7.84
7.75
7.66
7.57
7.49
7.4
7.32
7.25
7.19
7.13
7.08
7.02
6.98
6.94
6.91
6.88
6.85
6.83
6.8
6.78
6.77
6.75
6.73
6.72
6.7
6.69
6.68
6.67
6.66
6.65
6.64
6.63
6.62
6.61
6.6
6.59
6.59
6.58
6.57
6.57
6.56
6.55
6.54
6.54
6.53
6.52
6.52
6.51
6.51
6.5
6.49
6.49
6.48
6.47
6.47
6.46
6.45
6.45
6.44
6.44
6.43
6.42
6.42
6.41
6.41
6.4
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.35
6.35
6.34
37.2
37.0
36.8
36.5
36.2
35.8
35.4
34.8
34.0
32.9
31.4
29.3
26.5
22.5
17.4
12.2
9.87
9.64
9.47
9.31
9.15
9.0
8.87
8.74
8.61
8.5
8.39
8.28
8.17
8.06
7.97
7.87
7.78
7.69
7.61
7.52
7.44
7.35
7.27
7.2
7.13
7.08
7.03
6.98
6.94
6.91
6.87
6.84
6.82
6.79
6.76
6.74
6.72
6.7
6.68
6.68
6.65
6.64
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.52
6.52
6.51
6.5
6.49
6.49
6.48
6.47
6.46
6.45
6.45
6.44
6.43
6.42
6.41
6.41
6.4
6.39
6.38
6.38
6.37
6.36
6.36
6.35
6.34
6.34
6.33
6.33
6.32
6.31
6.31
37.4
37.1
36.7
36.3
35.8
35.1
34.2
33.0
31.3
28.9
25.5
20.9
15.0
10.3
9.22
9.05
8.89
8.74
8.6
8.46
8.33
8.21
8.1
7.99
7.89
7.79
7.7
7.6
7.52
7.43
7.34
7.25
7.17
7.11
7.04
6.99
6.94
6.89
6.86
6.83
6.8
6.78
6.75
6.72
6.69
6.67
6.66
6.63
6.62
6.61
6.59
6.58
6.57
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.49
6.48
6.47
6.46
6.45
6.44
6.44
6.43
6.42
6.41
6.4
6.4
6.39
6.38
6.38
6.37
6.36
6.35
6.35
6.34
6.33
6.33
6.32
6.31
6.3
6.3
6.29
6.28
6.28
6.27
6.26
6.26
6.25
6.25
6.24
6.24
6.23
6.23
6.23
6.24
37.7
37.2
36.6
35.9
35.1
33.9
32.5
30.4
27.6
23.6
18.2
12.5
9.55
9.28
9.11
8.94
8.78
8.63
8.49
8.36
8.24
8.13
8.02
7.92
7.82
7.73
7.63
7.54
7.46
7.37
7.29
7.22
7.15
7.09
7.04
6.99
6.94
6.9
6.86
6.83
6.81
6.78
6.76
6.73
6.71
6.69
6.67
6.66
6.64
6.63
6.61
6.6
6.59
6.58
6.57
6.56
6.56
6.54
6.54
6.52
6.51
6.51
6.5
6.49
6.48
6.47
6.46
6.46
6.45
6.44
6.43
6.42
6.41
6.41
6.4
6.39
6.38
6.37
6.37
6.36
6.35
6.35
6.34
6.33
6.33
6.32
6.31
6.3
6.29
6.28
6.27
6.26
6.25
6.24
6.23
6.22
6.21
6.21
6.2
6.2
37.2
36.9
36.5
36.0
35.4
34.7
33.6
32.2
30.2
27.4
23.5
18.4
13.1
10.1
9.6
9.4
9.2
9.02
8.86
8.69
8.53
8.39
8.25
8.11
7.99
7.87
7.77
7.67
7.57
7.48
7.39
7.3
7.21
7.13
7.07
7.0
6.95
6.9
6.85
6.82
6.79
6.77
6.74
6.71
6.69
6.67
6.65
6.64
6.62
6.61
6.6
6.59
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.48
6.47
6.46
6.45
6.44
6.43
6.42
6.4
6.39
6.38
6.37
6.36
6.35
6.34
6.33
6.33
6.32
6.31
6.3
6.29
6.28
6.27
6.26
6.25
6.25
6.24
6.23
6.23
6.22
6.23
6.24
6.24
6.24
6.24
6.24
6.27
6.3
6.25
6.27
37.5
37.2
36.8
36.4
35.8
35.1
34.0
32.6
30.7
28.1
24.4
19.4
13.5
9.8
9.22
9.04
8.87
8.71
8.56
8.43
8.29
8.17
8.05
7.95
7.84
7.75
7.65
7.56
7.47
7.38
7.29
7.21
7.13
7.06
7.0
6.95
6.9
6.86
6.83
6.8
6.77
6.74
6.72
6.69
6.67
6.65
6.63
6.62
6.61
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.5
6.5
6.49
6.48
6.47
6.47
6.46
6.46
6.45
6.44
6.43
6.43
6.42
6.42
6.41
6.4
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.33
6.32
6.32
6.32
6.33
6.31
6.32
6.31
6.3
6.3
6.3
37.0
36.7
36.3
35.7
35.1
34.2
33.1
31.5
29.3
26.2
21.9
16.3
11.2
9.39
9.19
9.03
8.87
8.72
8.57
8.43
8.3
8.18
8.07
7.95
7.85
7.75
7.66
7.56
7.48
7.39
7.31
7.23
7.17
7.1
7.05
7.0
6.96
6.92
6.89
6.86
6.82
6.8
6.77
6.74
6.71
6.69
6.67
6.66
6.64
6.63
6.61
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.51
6.51
6.5
6.49
6.48
6.47
6.46
6.45
6.44
6.43
6.42
6.41
6.4
6.4
6.39
6.38
6.37
6.36
6.35
6.34
6.34
6.33
6.32
6.31
6.32
6.31
6.31
6.3
6.3
6.3
6.29
6.29
6.29
6.28
6.27
6.27
6.26
6.26
6.25
6.24
6.24
37.4
36.9
36.3
35.5
34.5
33.1
31.3
28.7
25.2
20.3
14.4
10.2
9.35
9.17
9.01
8.85
8.71
8.58
8.45
8.33
8.22
8.12
8.01
7.91
7.82
7.73
7.65
7.56
7.47
7.38
7.29
7.23
7.16
7.1
7.05
7.0
6.95
6.91
6.88
6.85
6.82
6.79
6.77
6.75
6.73
6.71
6.7
6.68
6.67
6.66
6.65
6.64
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.56
6.56
6.55
6.54
6.53
6.53
6.52
6.51
6.51
6.5
6.49
6.49
6.48
6.47
6.47
6.46
6.46
6.45
6.44
6.44
6.43
6.43
6.42
6.41
6.41
6.4
6.4
6.39
6.39
6.38
6.37
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.34
6.33
36.7
36.2
35.5
34.6
33.4
31.7
29.4
26.2
21.8
16.1
11.0
9.51
9.32
9.14
8.97
8.8
8.66
8.52
8.38
8.26
8.15
8.05
7.95
7.86
7.76
7.67
7.58
7.49
7.4
7.32
7.23
7.16
7.11
7.05
7.0
6.96
6.91
6.88
6.85
6.82
6.79
6.77
6.75
6.73
6.71
6.69
6.68
6.67
6.66
6.64
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.53
6.52
6.51
6.5
6.49
6.49
6.48
6.47
6.47
6.46
6.45
6.44
6.44
6.43
6.42
6.42
6.41
6.41
6.4
6.39
6.39
6.38
6.37
6.37
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.32
6.32
6.31
6.31
6.31
6.3
6.3
6.3
37.2
37.0
36.7
36.5
36.1
35.7
35.2
34.5
33.6
32.4
30.8
28.5
25.3
20.9
15.6
11.3
9.87
9.68
9.51
9.33
9.16
9.0
8.85
8.7
8.56
8.43
8.3
8.18
8.07
7.97
7.87
7.77
7.68
7.59
7.5
7.41
7.33
7.24
7.16
7.09
7.03
6.97
6.93
6.88
6.84
6.81
6.78
6.76
6.73
6.71
6.68
6.67
6.65
6.64
6.62
6.61
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.53
6.52
6.51
6.5
6.49
6.49
6.48
6.47
6.47
6.46
6.45
6.45
6.44
6.43
6.42
6.42
6.41
6.41
6.4
6.4
6.39
6.39
6.38
6.37
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.33
6.32
6.32
36.7
36.1
35.3
34.2
32.6
30.5
27.5
23.4
17.9
12.3
9.69
9.39
9.21
9.06
8.91
8.78
8.65
8.53
8.41
8.3
8.18
8.07
7.96
7.86
7.76
7.66
7.56
7.47
7.39
7.3
7.21
7.13
7.06
6.99
6.94
6.89
6.84
6.81
6.77
6.74
6.72
6.69
6.66
6.64
6.62
6.6
6.58
6.56
6.54
6.53
6.51
6.5
6.49
6.47
6.46
6.45
6.44
6.42
6.41
6.4
6.39
6.38
6.37
6.36
6.34
6.33
6.32
6.32
6.31
6.3
6.29
6.28
6.27
6.27
6.26
6.25
6.24
6.24
6.23
6.23
6.22
6.22
6.21
6.21
6.21
6.2
6.22
6.21
6.22
6.21
6.21
6.2
6.22
6.21
6.25
6.25
6.28
6.28
6.29
6.29
37.1
36.8
36.5
36.1
35.7
35.1
34.4
33.3
31.9
30.0
27.4
23.7
18.7
13.0
9.82
9.36
9.16
8.96
8.78
8.61
8.45
8.29
8.14
8.01
7.88
7.77
7.66
7.57
7.47
7.39
7.3
7.21
7.15
7.08
7.02
6.97
6.91
6.88
6.84
6.81
6.78
6.75
6.72
6.7
6.68
6.66
6.65
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.51
6.5
6.49
6.48
6.48
6.47
6.46
6.46
6.45
6.44
6.44
6.43
6.42
6.41
6.41
6.4
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.32
6.32
6.32
6.31
6.31
6.31
6.3
6.3
6.3
37.0
36.7
36.2
35.7
34.9
34.0
32.6
30.7
28.2
24.6
19.8
14.2
10.3
9.55
9.34
9.14
8.96
8.79
8.63
8.47
8.33
8.19
8.06
7.95
7.84
7.73
7.63
7.53
7.44
7.35
7.25
7.17
7.09
7.03
6.97
6.92
6.88
6.84
6.81
6.77
6.74
6.72
6.69
6.67
6.66
6.63
6.62
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.49
6.48
6.47
6.46
6.46
6.45
6.44
6.44
6.43
6.43
6.42
6.41
6.4
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.34
6.33
6.33
6.32
6.32
6.32
6.32
6.31
6.31
6.3
6.3
6.3
6.31
6.31
6.3
37.4
37.0
36.6
36.1
35.5
34.7
33.6
32.1
30.1
27.2
23.3
18.1
12.7
10.0
9.71
9.52
9.34
9.17
9.01
8.85
8.71
8.57
8.44
8.33
8.22
8.11
8.01
7.92
7.83
7.74
7.65
7.56
7.47
7.38
7.3
7.23
7.16
7.1
7.05
7.0
6.96
6.92
6.89
6.86
6.83
6.81
6.78
6.75
6.74
6.73
6.71
6.69
6.68
6.66
6.65
6.64
6.63
6.62
6.61
6.59
6.58
6.57
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.5
6.5
6.49
6.48
6.47
6.46
6.45
6.44
6.43
6.42
6.41
6.4
6.4
6.39
6.38
6.37
6.36
6.35
6.34
6.33
6.32
6.31
6.3
6.29
6.28
6.27
6.27
6.26
6.26
6.27
6.25
37.7
37.4
36.9
36.4
35.8
34.9
33.8
32.2
30.0
26.9
22.6
16.9
11.2
9.23
9.05
8.88
8.73
8.58
8.45
8.32
8.22
8.12
8.02
7.92
7.83
7.74
7.65
7.56
7.47
7.39
7.31
7.23
7.16
7.11
7.06
7.01
6.97
6.93
6.89
6.86
6.83
6.8
6.78
6.76
6.73
6.71
6.7
6.68
6.67
6.65
6.64
6.63
6.62
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.48
6.47
6.46
6.45
6.45
6.44
6.43
6.42
6.41
6.4
6.39
6.39
6.38
6.37
6.37
6.36
6.35
6.35
6.34
6.34
6.33
6.32
6.31
6.31
6.3
6.3
6.29
6.29
6.28
6.28
6.27
6.27
6.27
6.26
6.26
37.6
37.2
36.8
36.1
35.2
34.1
32.5
30.3
27.4
23.2
17.8
12.4
10.1
9.82
9.62
9.43
9.25
9.08
8.91
8.76
8.61
8.48
8.35
8.23
8.12
8.02
7.92
7.83
7.74
7.65
7.56
7.46
7.38
7.31
7.24
7.18
7.12
7.06
7.02
6.98
6.95
6.92
6.89
6.86
6.83
6.8
6.77
6.75
6.73
6.72
6.7
6.68
6.67
6.65
6.64
6.63
6.61
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.48
6.47
6.46
6.45
6.44
6.42
6.42
6.4
6.39
6.38
6.37
6.36
6.35
6.34
6.33
6.32
6.31
6.3
6.29
6.28
6.27
6.27
6.26
6.25
6.24
6.26
6.27
6.27
6.28
6.28
6.29
36.9
36.3
35.7
34.9
33.7
32.2
30.1
27.1
23.0
17.4
11.6
9.27
9.04
8.87
8.71
8.57
8.42
8.29
8.18
8.08
7.97
7.87
7.78
7.68
7.59
7.51
7.42
7.34
7.26
7.19
7.12
7.07
7.02
6.98
6.94
6.9
6.87
6.83
6.8
6.78
6.75
6.73
6.71
6.69
6.68
6.67
6.65
6.64
6.63
6.61
6.6
6.59
6.58
6.56
6.55
6.54
6.53
6.53
6.52
6.51
6.5
6.49
6.48
6.47
6.47
6.46
6.45
6.45
6.44
6.43
6.43
6.42
6.41
6.41
6.4
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.32
6.32
6.32
6.31
6.31
6.31
6.3
6.3
6.3
6.3
6.29
6.29
38.0
37.8
37.5
37.3
37.0
36.7
36.3
35.8
35.1
34.3
33.1
31.5
29.3
26.3
22.0
16.5
11.2
9.36
9.15
8.96
8.79
8.62
8.47
8.33
8.2
8.09
7.98
7.87
7.77
7.68
7.58
7.49
7.41
7.32
7.24
7.17
7.1
7.04
6.99
6.94
6.9
6.88
6.84
6.81
6.79
6.76
6.73
6.71
6.69
6.67
6.65
6.64
6.63
6.62
6.61
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.53
6.52
6.51
6.5
6.5
6.49
6.48
6.47
6.47
6.46
6.45
6.44
6.44
6.43
6.42
6.42
6.41
6.41
6.41
6.39
6.39
6.39
6.39
6.37
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.34
6.34
6.33
6.33
6.32
6.32
37.5
37.2
36.7
36.1
35.4
34.4
33.1
31.2
28.7
25.2
20.4
14.9
11.0
9.99
9.81
9.63
9.45
9.28
9.11
8.95
8.8
8.66
8.52
8.4
8.29
8.18
8.08
7.98
7.89
7.8
7.71
7.62
7.53
7.45
7.36
7.28
7.2
7.13
7.07
7.02
6.97
6.93
6.89
6.85
6.83
6.8
6.77
6.75
6.73
6.71
6.69
6.67
6.65
6.64
6.63
6.62
6.61
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.52
6.52
6.51
6.51
6.5
6.49
6.48
6.47
6.47
6.46
6.45
6.45
6.44
6.43
6.43
6.42
6.42
6.41
6.4
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.33
37.1
36.7
36.1
35.4
34.5
33.3
31.6
29.2
25.9
21.3
15.5
10.6
9.29
9.15
9.02
8.89
8.77
8.65
8.54
8.43
8.31
8.2
8.1
7.99
7.88
7.77
7.68
7.59
7.5
7.41
7.33
7.25
7.18
7.12
7.06
7.01
6.97
6.93
6.9
6.87
6.84
6.81
6.79
6.75
6.74
6.71
6.69
6.67
6.66
6.64
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.53
6.53
6.52
6.51
6.5
6.5
6.49
6.48
6.48
6.47
6.46
6.46
6.45
6.44
6.43
6.43
6.42
6.42
6.41
6.41
6.4
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.33
6.32
6.32
6.32
37.0
36.7
36.3
35.9
35.3
34.5
33.5
32.2
30.3
27.7
24.0
19.0
13.1
9.56
9.13
8.97
8.81
8.67
8.54
8.41
8.3
8.2
8.1
8.01
7.92
7.84
7.76
7.67
7.58
7.5
7.41
7.33
7.25
7.19
7.14
7.1
7.05
7.01
6.97
6.93
6.9
6.87
6.84
6.81
6.79
6.76
6.74
6.72
6.71
6.69
6.68
6.67
6.66
6.65
6.64
6.62
6.61
6.6
6.59
6.58
6.57
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.48
6.47
6.46
6.45
6.44
6.43
6.42
6.42
6.41
6.4
6.39
6.38
6.38
6.37
6.36
6.36
6.35
6.34
6.34
6.33
6.32
6.32
6.31
6.3
6.3
6.29
6.29
6.28
6.28
6.27
6.27
6.26
37.1
36.7
36.2
35.6
34.8
33.8
32.3
30.3
27.6
23.8
18.6
12.9
9.65
9.21
9.04
8.87
8.71
8.55
8.41
8.27
8.15
8.03
7.92
7.81
7.71
7.61
7.52
7.43
7.34
7.25
7.17
7.1
7.04
6.99
6.94
6.89
6.85
6.82
6.79
6.77
6.74
6.72
6.69
6.67
6.65
6.64
6.62
6.61
6.6
6.59
6.58
6.57
6.55
6.55
6.54
6.53
6.52
6.51
6.5
6.5
6.49
6.48
6.47
6.47
6.46
6.45
6.44
6.44
6.43
6.42
6.42
6.41
6.4
6.4
6.39
6.39
6.39
6.37
6.37
6.37
6.36
6.35
6.35
6.34
6.34
6.34
6.33
6.33
6.33
6.32
6.31
6.31
6.31
6.3
6.3
6.3
6.3
6.3
6.3
6.31
37.8
37.4
37.0
36.4
35.7
34.7
33.4
31.5
28.9
25.3
20.4
14.7
10.8
9.93
9.69
9.46
9.25
9.05
8.87
8.69
8.52
8.37
8.23
8.09
7.97
7.85
7.74
7.65
7.55
7.45
7.36
7.27
7.19
7.12
7.05
6.99
6.94
6.89
6.86
6.83
6.8
6.77
6.74
6.72
6.69
6.67
6.65
6.64
6.62
6.61
6.6
6.59
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.5
6.5
6.49
6.48
6.47
6.46
6.46
6.45
6.44
6.44
6.43
6.42
6.41
6.4
6.39
6.39
6.38
6.37
6.36
6.36
6.35
6.34
6.34
6.33
6.32
6.31
6.31
6.3
6.3
6.29
6.28
6.29
6.28
6.27
6.27
6.26
6.26
6.25
6.26
6.25
6.25
37.5
37.0
36.4
35.7
34.8
33.5
31.8
29.4
26.0
21.4
15.6
10.8
9.49
9.32
9.15
8.99
8.83
8.68
8.55
8.42
8.3
8.18
8.07
7.96
7.87
7.77
7.68
7.59
7.5
7.42
7.34
7.27
7.2
7.14
7.08
7.03
6.99
6.95
6.92
6.88
6.85
6.82
6.79
6.77
6.75
6.73
6.72
6.7
6.69
6.68
6.67
6.65
6.64
6.64
6.63
6.62
6.61
6.6
6.6
6.59
6.58
6.57
6.57
6.56
6.55
6.54
6.54
6.53
6.52
6.51
6.51
6.5
6.49
6.49
6.48
6.47
6.47
6.46
6.45
6.45
6.44
6.43
6.43
6.42
6.42
6.41
6.42
6.4
6.4
6.39
6.39
6.39
6.39
6.4
6.39
6.4
6.38
6.38
6.37
6.37
36.9
36.5
35.9
35.2
34.2
32.9
31.0
28.4
24.8
19.8
13.8
9.75
9.04
8.9
8.76
8.64
8.52
8.41
8.3
8.19
8.08
7.98
7.87
7.78
7.68
7.59
7.5
7.41
7.33
7.25
7.19
7.13
7.07
7.02
6.97
6.94
6.9
6.87
6.84
6.82
6.79
6.77
6.75
6.72
6.7
6.68
6.67
6.66
6.64
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.54
6.53
6.52
6.51
6.5
6.5
6.49
6.48
6.47
6.47
6.46
6.45
6.44
6.44
6.43
6.43
6.42
6.42
6.41
6.4
6.39
6.38
6.38
6.37
6.37
6.36
6.35
6.35
6.34
6.33
6.33
6.32
6.32
6.31
6.3
6.3
6.3
6.29
6.29
6.29
6.28
37.9
37.6
37.2
36.8
36.2
35.5
34.5
33.2
31.3
28.8
25.3
20.4
14.3
10.0
9.19
9.01
8.84
8.69
8.55
8.41
8.28
8.17
8.06
7.95
7.84
7.75
7.65
7.56
7.47
7.38
7.3
7.21
7.14
7.08
7.02
6.97
6.92
6.88
6.85
6.82
6.79
6.76
6.73
6.71
6.68
6.66
6.64
6.63
6.61
6.6
6.58
6.57
6.56
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.49
6.48
6.47
6.46
6.45
6.45
6.44
6.43
6.42
6.42
6.42
6.4
6.4
6.39
6.38
6.38
6.37
6.36
6.36
6.36
6.34
6.34
6.33
6.33
6.32
6.31
6.31
6.3
6.3
6.29
6.29
6.29
6.28
6.28
6.28
6.28
6.27
6.27
6.27
6.26
36.6
36.0
35.2
34.2
32.8
31.0
28.4
24.7
19.8
14.1
10.3
9.56
9.37
9.19
9.01
8.84
8.68
8.53
8.39
8.27
8.15
8.04
7.94
7.84
7.74
7.64
7.55
7.47
7.38
7.29
7.21
7.14
7.08
7.03
6.98
6.94
6.9
6.86
6.84
6.81
6.78
6.76
6.73
6.71
6.69
6.67
6.66
6.64
6.63
6.62
6.6
6.59
6.58
6.57
6.56
6.55
6.54
6.54
6.53
6.52
6.51
6.51
6.5
6.49
6.49
6.47
6.47
6.46
6.45
6.45
6.44
6.43
6.43
6.42
6.41
6.4
6.4
6.39
6.38
6.38
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.32
6.32
6.31
6.31
6.3
6.3
6.3
6.29
6.29
6.29
6.28
37.7
37.3
36.7
36.1
35.3
34.2
32.7
30.6
27.8
23.8
18.4
12.5
9.53
9.24
9.07
8.9
8.74
8.6
8.46
8.33
8.22
8.11
8.0
7.9
7.81
7.71
7.62
7.53
7.44
7.36
7.27
7.19
7.12
7.06
7.02
6.97
6.93
6.89
6.86
6.83
6.8
6.77
6.75
6.73
6.71
6.69
6.67
6.66
6.64
6.63
6.62
6.61
6.6
6.59
6.58
6.57
6.55
6.55
6.54
6.53
6.52
6.51
6.5
6.49
6.48
6.47
6.47
6.46
6.45
6.44
6.43
6.42
6.41
6.4
6.39
6.38
6.38
6.37
6.36
6.35
6.34
6.34
6.33
6.32
6.32
6.31
6.3
6.3
6.29
6.29
6.29
6.28
6.28
6.27
6.27
6.26
6.26
6.25
6.25
6.25
37.8
37.4
37.0
36.5
35.9
35.1
33.9
32.4
30.3
27.3
23.2
17.6
11.8
9.58
9.34
9.17
9.01
8.85
8.71
8.57
8.43
8.31
8.2
8.1
8.0
7.91
7.82
7.74
7.65
7.56
7.47
7.39
7.32
7.26
7.2
7.15
7.11
7.06
7.02
6.98
6.95
6.92
6.89
6.86
6.83
6.81
6.8
6.77
6.75
6.74
6.72
6.71
6.7
6.68
6.67
6.66
6.65
6.64
6.63
6.62
6.6
6.59
6.58
6.57
6.56
6.56
6.55
6.54
6.53
6.52
6.52
6.51
6.5
6.49
6.48
6.48
6.47
6.46
6.45
6.45
6.44
6.44
6.43
6.42
6.41
6.41
6.4
6.39
6.39
6.38
6.38
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
37.7
37.3
36.9
36.3
35.5
34.5
33.1
31.2
28.5
24.8
19.7
14.0
10.3
9.74
9.53
9.34
9.16
8.99
8.82
8.65
8.5
8.36
8.23
8.11
7.99
7.88
7.78
7.68
7.59
7.49
7.4
7.31
7.23
7.15
7.08
7.02
6.97
6.92
6.88
6.85
6.82
6.79
6.76
6.73
6.71
6.69
6.66
6.65
6.63
6.61
6.6
6.59
6.57
6.56
6.55
6.54
6.54
6.52
6.51
6.51
6.5
6.49
6.48
6.48
6.47
6.46
6.45
6.45
6.44
6.44
6.44
6.42
6.41
6.41
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.35
6.35
6.34
6.34
6.33
6.34
6.32
6.32
6.32
6.31
6.31
6.3
6.3
6.29
6.29
6.29
6.29
6.3
37.9
37.6
37.3
36.9
36.4
35.8
34.9
33.7
32.1
30.0
26.9
22.7
17.2
11.8
9.78
9.57
9.39
9.22
9.05
8.89
8.75
8.61
8.48
8.35
8.24
8.13
8.03
7.94
7.85
7.76
7.67
7.58
7.49
7.4
7.32
7.24
7.18
7.12
7.06
7.01
6.96
6.93
6.89
6.86
6.83
6.8
6.77
6.75
6.73
6.71
6.69
6.67
6.66
6.65
6.64
6.62
6.61
6.6
6.59
6.58
6.56
6.55
6.54
6.53
6.53
6.52
6.51
6.5
6.49
6.48
6.48
6.47
6.46
6.45
6.45
6.44
6.43
6.42
6.41
6.41
6.39
6.39
6.38
6.37
6.36
6.35
6.34
6.33
6.33
6.32
6.3
6.29
6.28
6.27
6.26
6.25
6.24
6.23
6.22
6.21
37.8
37.4
37.0
36.5
35.8
34.9
33.7
32.0
29.8
26.7
22.4
16.9
11.7
9.91
9.66
9.48
9.31
9.14
8.98
8.83
8.69
8.56
8.43
8.32
8.21
8.11
8.01
7.9
7.8
7.7
7.61
7.52
7.43
7.35
7.27
7.21
7.15
7.1
7.05
7.0
6.95
6.91
6.88
6.85
6.82
6.79
6.76
6.74
6.73
6.72
6.7
6.69
6.68
6.67
6.66
6.65
6.64
6.62
6.61
6.61
6.6
6.59
6.58
6.57
6.56
6.56
6.55
6.54
6.53
6.52
6.52
6.51
6.5
6.49
6.49
6.48
6.47
6.46
6.46
6.45
6.45
6.44
6.43
6.43
6.42
6.42
6.41
6.4
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.34
6.34
36.9
36.6
36.2
35.7
35.1
34.3
33.1
31.6
29.4
26.4
22.3
17.0
11.8
9.76
9.54
9.36
9.19
9.03
8.87
8.73
8.59
8.46
8.34
8.22
8.11
8.01
7.91
7.81
7.72
7.63
7.55
7.46
7.37
7.29
7.21
7.14
7.08
7.02
6.97
6.93
6.89
6.86
6.83
6.79
6.76
6.74
6.71
6.69
6.67
6.66
6.64
6.63
6.61
6.6
6.59
6.58
6.56
6.55
6.54
6.53
6.52
6.52
6.51
6.5
6.49
6.49
6.48
6.47
6.47
6.46
6.45
6.44
6.44
6.43
6.42
6.42
6.41
6.41
6.4
6.39
6.39
6.38
6.38
6.37
6.37
6.36
6.36
6.35
6.35
6.34
6.34
6.33
6.33
6.32
6.32
6.31
6.31
6.31
6.31
6.3
36.7
36.2
35.6
34.8
33.6
32.1
30.0
27.1
23.0
17.7
12.2
9.75
9.5
9.32
9.15
8.99
8.84
8.7
8.56
8.43
8.32
8.21
8.11
8.02
7.93
7.84
7.75
7.66
7.57
7.48
7.4
7.32
7.26
7.2
7.14
7.09
7.05
7.0
6.97
6.93
6.9
6.87
6.84
6.82
6.79
6.77
6.75
6.73
6.71
6.7
6.69
6.67
6.66
6.65
6.64
6.63
6.62
6.61
6.6
6.59
6.58
6.58
6.56
6.56
6.55
6.54
6.54
6.53

In [113]:
ens_preds = torch.stack(learns).mean(0)

In [114]:
nn_ens_loss = torch.abs(ens_preds-tensor(val_dep)).mean()
nn_ens_loss

tensor(7.0507, grad_fn=<MeanBackward0>)

In [115]:
# Calculate MAE separately for each existing neural-network prediction.
with torch.no_grad():
    val_targets = tensor(val_dep)
    nn_member_maes = torch.stack([
        torch.abs(preds - val_targets).mean()
        for preds in learns
    ])

# Save the neural-network summary separately.
nn_ensemble_summary = {
    "Model family": "Neural network",
    "Mean individual MAE": nn_member_maes.mean().item(),
    "Lowest individual MAE": nn_member_maes.min().item(),
    "Ensemble MAE": nn_ens_loss.item(),
}

pd.DataFrame([nn_ensemble_summary]).round(4)

     Model family  Mean individual MAE  Lowest individual MAE  Ensemble MAE
0  Neural network               7.0721                 6.8014        7.0507

# Loss Scores

## 5 models in an ensemble

In [77]:
print(f"Linear model: {lin_loss}")
print(f"Linear model (ens): {lin_ens_loss}")
print(f"Neural net: {nn_loss}")
print(f"Neural net (ens): {nn_ens_loss}")

Linear model: 7.209723472595215
Linear model (ens): 6.810535907745361
Neural net: 7.254626750946045
Neural net (ens): 7.084789752960205

## 100 models in an ensemble

In [116]:
print(f"Linear model: {lin_loss}")
print(f"Linear model (ens): {lin_ens_loss}")
print(f"Neural net: {nn_loss}")
print(f"Neural net (ens): {nn_ens_loss}")

Linear model: 7.209723472595215
Linear model (ens): 6.8811211585998535
Neural net: 7.180288791656494
Neural net (ens): 7.0507283210754395

In [117]:
available_summaries = [
    globals()[name]
    for name in ("lin_ensemble_summary", "nn_ensemble_summary")
    if name in globals()
]

ensemble_comparison = pd.DataFrame(available_summaries).round(4)
ensemble_comparison

     Model family  Mean individual MAE  Lowest individual MAE  Ensemble MAE
0          Linear               7.0455                 6.7146        6.8811
1  Neural network               7.0721                 6.8014        7.0507